import keyword
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Literal
from xml.etree.ElementTree import Element

import pydantic
import pydantic_xml

NS = "http://relaxng.org/ns/structure/1.0"
_XSD_NUMERIC = {
    "int": "int",
    "integer": "int",
    "long": "int",
    "short": "int",
    "unsignedInt": "int",
    "unsignedLong": "int",
    "unsignedShort": "int",
    "positiveInteger": "int",
    "nonNegativeInteger": "int",
    "double": "float",
    "float": "float",
    "boolean": "bool",
}
PREAMBLE = """import typing
import pydantic
import pydantic_xml

# This file was automatically generated by relaxng-to-pydantic. Do not modify.
"""
_PRIMITIVES = {"str", "int", "float", "None"}


def is_reserved(name: str) -> bool:
    return (
        keyword.iskeyword(name)
        or hasattr(pydantic.BaseModel, name)
        or hasattr(pydantic_xml.BaseXmlModel, name)
    )


def escape_identifier(name: str) -> str:
    name = name.replace("-", "_")
    name = f"{name}_" if is_reserved(name) else name
    return name


def identifier(xml_name: str) -> str:
    """snake_case for an XML tag/attribute/define name, e.g. "trustGuestRxFilters"/"disk-source"
    -> "trust_guest_rx_filters"/"disk_source" - used for field names and class names alike."""
    out: list[str] = []
    for c in xml_name:
        if c == "-":
            if out and out[-1] != "_":
                out.append("_")
        elif c.isupper():
            if out and out[-1] != "_":
                out.append("_")
            out.append(c.lower())
        else:
            out.append(c)
    return escape_identifier("".join(out))


def ns_prefix(uri: str) -> str:
    """A namespace prefix from its URI's last non-version segment, e.g.
    "http://libvirt.org/schemas/domain/qemu/1.0" -> "qemu"."""
    segments = uri.replace("#", "/").replace(":", "/").split("/")
    words = [s for s in segments if s and not s.replace(".", "").isdigit()]
    return identifier(words[-1]) if words else "ns"


def inherit_ns(node: Element, ns: str = "") -> None:
    """RelaxNG's ns attribute applies to every <element> lexically beneath it that doesn't set
    its own - write it onto each element explicitly, since refs get resolved far from where the
    element was written."""
    ns = node.attrib.get("ns", ns)
    if node.tag == f"{{{NS}}}element":
        node.attrib["ns"] = ns
    for child in node:
        inherit_ns(child, ns)


def tag(node: Element) -> str:
    prefix, sep, local = node.tag.partition("}")
    assert sep and prefix == "{" + NS, f"not a RelaxNG node: {node.tag!r}"
    return local


def single_child(node: Element) -> Element | None:
    children = list(node)
    return children[0] if len(children) == 1 else None


def qualified_name(element: Element) -> tuple[str, str | None]:
    """An <element>'s (namespace, name) - same-named elements from different namespaces (e.g.
    qemu's vs xen's <commandline>) are different elements."""
    return element.attrib.get("ns", ""), element.attrib.get("name")


def param(node: Element, name: str) -> str | None:
    return next(
        (p.text for p in node if tag(p) == "param" and p.attrib.get("name") == name),
        None,
    )


def as_group(children: list[Element]) -> Element:
    if len(children) == 1:
        return children[0]
    group = ET.Element(f"{{{NS}}}group")
    group.extend(children)
    return group


@dataclass(frozen=True)
class PythonType:
    origin: Literal["Literal", "List", "Optional", "Union"] | None = None
    text: str = ""
    literals: tuple[str, ...] = ()
    args: tuple["PythonType", ...] = ()

    @staticmethod
    def opaque(text: str) -> "PythonType":
        return PythonType(text=text)

    @staticmethod
    def literal(*values: str) -> "PythonType":
        return PythonType(origin="Literal", literals=values)

    @staticmethod
    def from_xsd(node: Element) -> "PythonType":
        base = _XSD_NUMERIC.get(node.attrib.get("type", "string"), "str")
        pattern = param(node, "pattern")
        if pattern and base == "str":
            return PythonType.opaque(
                f"typing.Annotated[str, pydantic.Field(pattern={pattern!r})]"
            )
        return PythonType.opaque(base)

    @staticmethod
    def from_hex_int_choice(branches: list[Element]) -> "PythonType | None":
        if not all(tag(b) == "data" for b in branches):
            return None
        numeric = [
            b
            for b in branches
            if _XSD_NUMERIC.get(b.attrib.get("type", "string"), "str")
            in ("int", "float")
        ]
        hexish = [b for b in branches if b not in numeric]
        if not numeric or not hexish:
            return None
        for b in hexish:
            if b.attrib.get("type", "string") != "string":
                return None
            if "0x" not in (param(b, "pattern") or "").lower():
                return None
        # all digits is the decimal branch ("10" is ten), anything else the hex one ("0x10", "1f")
        return PythonType.opaque(
            "typing.Annotated[int, pydantic.BeforeValidator(lambda v: "
            "(int(v) if v.isdigit() else int(v, 16)) if isinstance(v, str) else v)]"
        )

    @staticmethod
    def from_relaxng(
        node: Element, resolver: "Resolver", name_override: str | None = None
    ) -> "PythonType":
        t = tag(node)
        if t == "text":
            return PythonType.opaque("str")
        if t == "data":
            return PythonType.from_xsd(node)
        if t == "value":
            return PythonType.literal(repr(node.text or ""))
        if t in ("empty", "notAllowed"):
            return PythonType.opaque("None")
        if t == "ref":
            return resolver.resolve_ref(node.attrib["name"])
        if t == "element":
            return PythonType.opaque(resolver.resolve_element(node, name_override))
        if t == "choice":
            branches = list(node)
            if hexint := PythonType.from_hex_int_choice(branches):
                return hexint
            types: list[PythonType] = []
            for b in branches:
                v = PythonType.from_relaxng(b, resolver, name_override)
                if v not in types:
                    types.append(v)
            return PythonType.merge(types)
        if t in ("group", "optional"):
            child = single_child(node)
            if child is None:
                raise KeyError(
                    f"<{t}> with more than one pattern has no single value type"
                )
            inner = PythonType.from_relaxng(child, resolver, name_override)
            if t == "optional" and inner.origin != "Optional":
                return inner.as_optional()
            return inner
        raise KeyError(f"<{t}> has no value type")

    @staticmethod
    def merge(types: "list[PythonType]") -> "PythonType":
        if len(types) == 1:
            return types[0]
        if all(t.origin == "Literal" for t in types):
            values: list[str] = []
            for t in types:
                for v in t.literals:
                    if v not in values:
                        values.append(v)
            return PythonType.literal(*values)
        if any(t.origin == "List" for t in types):
            inner = PythonType.merge(
                [t.args[0] if t.origin == "List" else t for t in types]
            )
            return inner.as_list()
        if all(t.origin == "Optional" for t in types):
            inner = PythonType.merge([t.args[0] for t in types])
            return inner.as_optional()
        return PythonType(origin="Union", args=tuple(types))

    def as_list(self) -> "PythonType":
        return PythonType(origin="List", args=(self,))

    def as_optional(self) -> "PythonType":
        return PythonType(origin="Optional", args=(self,))

    def escape_identifier(self) -> str | None:
        return self.text if self.origin is None else None

    def unwrap_escape_identifier(self) -> str | None:
        if self.origin == "List" and self.args[0].origin is None:
            return self.args[0].text
        return self.escape_identifier()

    def class_refs(self) -> list[str]:
        if self.origin is None:
            return [self.text.strip('"')]
        return [ref for a in self.args for ref in a.class_refs()]

    def remap(self, rename: dict[str, str]) -> "PythonType":
        """Swap every placeholder class name for its final one (see Resolver.assign_names) -
        used once, at the very end, after every class in the file is known."""
        if self.origin is None:
            quoted = self.text.startswith('"')
            bare = self.text.strip('"')
            if bare in rename:
                new = rename[bare]
                return PythonType.opaque(f'"{new}"' if quoted else new)
            return self
        return replace(self, args=tuple(a.remap(rename) for a in self.args))

    def render(self) -> str:
        if self.origin is None:
            bare = self.text.strip('"')
            if bare not in _PRIMITIVES and bare.isidentifier():
                aliased = f"_{bare}"
                return f'"{aliased}"' if self.text.startswith('"') else aliased
            return self.text
        if self.origin == "Literal":
            return "typing.Literal[" + ", ".join(self.literals) + "]"
        if self.origin == "List":
            return f"typing.List[{self.args[0].render()}]"
        if self.origin == "Optional":
            return f"typing.Optional[{self.args[0].render()}]"
        return f"typing.Union[{', '.join(a.render() for a in self.args)}]"


@dataclass(frozen=True)
class GeneratedField:
    name: str
    xml_name: str | None  # None only for the unrepresentable <anyName/> wildcard
    type: PythonType
    kind: Literal["attr", "element"]
    optional: bool = False
    min_length: int | None = None
    ns: str = ""

    def repeated(self, optional: bool, min_length: int | None) -> "GeneratedField":
        return replace(
            self,
            name=f"{self.name.rstrip('_')}_list",
            type=self.type.as_list(),
            optional=optional,
            min_length=min_length,
        )

    def remap(self, rename: dict[str, str]) -> "GeneratedField":
        return replace(self, type=self.type.remap(rename))


def field_line(f: GeneratedField) -> str:
    call = "attr" if f.kind == "attr" else "element"
    args = (
        []
        if f.xml_name is None
        else [f"{'name' if f.kind == 'attr' else 'tag'}={f.xml_name!r}"]
    )
    if f.min_length is not None:
        args.append(f"min_length={f.min_length}")
    type_ = f.type
    if f.optional:
        args.append("default=None")
        type_ = type_.as_optional()
    return f"\t{f.name}: {type_.render()} = pydantic_xml.{call}({', '.join(args)})"


def dedupe_fields(fields: list[GeneratedField]) -> list[GeneratedField]:
    """Give every field in a class a unique name, in the rare case an attribute and an element
    (or two elements reached through unrelated paths) resolve to the same Python name."""
    seen: dict[str, int] = {}
    out = []
    for f in fields:
        n = seen.get(f.name, 0) + 1
        seen[f.name] = n
        out.append(f if n == 1 else replace(f, name=f"{f.name}{n}"))
    return out


@dataclass
class GeneratedModel:
    fields: list[GeneratedField] = field(default_factory=list)
    body: PythonType | None = None
    body_optional: bool = False
    unordered: bool = False

    def __add__(self, other: "GeneratedModel") -> "GeneratedModel":
        assert self.body is None or other.body is None, "two text bodies in one group"
        return GeneratedModel(
            self.fields + other.fields,
            self.body or other.body,
            self.body_optional or other.body_optional,
            self.unordered or other.unordered,
        )

    @property
    def search_mode(self) -> str:
        return "unordered" if self.unordered else "strict"

    def render_lines(self, ns: str = "") -> str:
        """`ns` is the enclosing class's own namespace - a field for an element from a different
        one is prefixed with it (e.g. "qemu_commandline"), so same-named elements from several
        namespaces don't collide."""
        fields = dedupe_fields(
            [
                replace(f, name=f"{ns_prefix(f.ns)}_{f.name}")
                if f.ns and f.ns != ns
                else f
                for f in self.fields
            ]
        )
        lines = []
        if self.body is not None:
            body_type = self.body.as_optional() if self.body_optional else self.body
            default = " = None" if self.body_optional else ""
            lines.append(f"\tvalue: {body_type.render()}{default}")
        lines += [field_line(f) for f in fields]
        return "\n".join(lines) if lines else "\tpass"

    def remap(self, rename: dict[str, str]) -> "GeneratedModel":
        return replace(
            self,
            fields=[f.remap(rename) for f in self.fields],
            body=self.body.remap(rename) if self.body is not None else None,
        )


@dataclass
class GeneratedClass:
    name: str
    xml_tag: str
    model: GeneratedModel
    ns: str = ""
    forbid_extra: bool = False

    def render(self) -> str:
        lines = self.model.render_lines(self.ns)
        if self.forbid_extra:
            lines = "\tmodel_config = {'extra': 'forbid'}\n" + lines
        prefix = ns_prefix(self.ns)
        ns_args = (
            f", ns={prefix!r}, nsmap={{{prefix!r}: {self.ns!r}}}" if self.ns else ""
        )
        header = (
            f"class {self.name}(pydantic_xml.BaseXmlModel, tag={self.xml_tag!r}{ns_args}, "
            f"search_mode={self.model.search_mode!r}):"
        )
        return f"{header}\n{lines}\n\n_{self.name} = {self.name}"

    def remap(self, rename: dict[str, str]) -> "GeneratedClass":
        return replace(self, name=rename[self.name], model=self.model.remap(rename))


def collect(root: Element, base_dir: Path) -> tuple[dict[str, Element], Element | None]:
    inherit_ns(root)
    if tag(root) != "grammar":
        return {}, root
    defines: dict[str, Element] = {}
    start = None
    for child in root:
        t = tag(child)
        if t == "include":
            included = ET.parse(base_dir / child.attrib["href"]).getroot()
            defines.update(collect(included, base_dir)[0])
        elif t == "define":
            defines[child.attrib["name"]] = as_group(list(child))
        elif t == "start":
            start = as_group(list(child))
    return defines, start


def pick_name(
    base: str, parents: tuple[str, ...], used: set[str], allow_bare: bool
) -> str:
    """`base` if free and allowed, else prefixed with successively more of the ancestor chain
    (closest parent first: "entry" -> "base_board_entry" -> "sysinfo_base_board_entry" -> ...)
    until free - never a number, since a number says nothing about what actually distinguishes
    two classes. `allow_bare=False` (multiple classes contending for the same base name - see
    Resolver.assign_names) skips the bare candidate entirely. A word the chain already ends with
    (e.g. an <address> ref wrapping an <element name="address">) is dropped rather than repeated
    - "address_address" tells you nothing "address" didn't. Only if the *entire* chain is somehow
    still not enough does the closest parent repeat."""
    start = len(parents) if allow_bare else len(parents) - 1
    candidate = base
    for i in range(start, -1, -1):
        prefix_words = [w for s in parents[i:] for w in s.split("_") if w]
        if prefix_words and prefix_words[-1] == base:
            prefix_words.pop()
        candidate = "_".join([*prefix_words, base])
        if candidate not in used:
            used.add(candidate)
            return candidate
    prefix = parents[0] if parents else base
    if not allow_bare and candidate == base:
        candidate = f"{prefix}_{candidate}"
    while candidate in used:
        candidate = f"{prefix}_{candidate}"
    used.add(candidate)
    return candidate


class Resolver:
    def __init__(self, defines: dict[str, Element]) -> None:
        self.defines = defines
        self.classes: dict[
            str, GeneratedClass
        ] = {}  # keyed by placeholder until assign_names
        self.pending: dict[
            str, tuple[str, tuple[str, ...]]
        ] = {}  # placeholder -> (base, parents)
        self.ref_cache: dict[str, PythonType] = {}
        self.refs_in_progress: set[str] = set()
        self.mixins_in_progress: set[str] = set()
        self.element_cache: dict[int, str] = {}
        self.class_by_shape: dict[tuple[str, str, str, str], str] = {}
        self.truncated_cycles = 0

    def resolve_pattern(
        self, node: Element, optional: bool = False, parents: tuple[str, ...] = ()
    ) -> GeneratedModel:
        t = tag(node)
        if t == "element":
            xml_tag = node.attrib.get("name")  # None for the <anyName/> wildcard
            cls = self.resolve_element(node, parents=parents)
            f = GeneratedField(
                identifier(xml_tag or ""),
                xml_tag,
                PythonType.opaque(cls),
                "element",
                optional,
                ns=node.attrib.get("ns", ""),
            )
            return GeneratedModel(fields=[f])
        if t == "attribute":
            xml_name = node.attrib["name"]
            children = list(node)
            value_type = (
                PythonType.from_relaxng(children[0], self)
                if children
                else PythonType.opaque("str")
            )
            return GeneratedModel(
                fields=[
                    GeneratedField(
                        identifier(xml_name),
                        xml_name,
                        value_type,
                        "attr",
                        optional,
                    )
                ]
            )
        if t in ("notAllowed", "grammar", "empty"):
            return GeneratedModel()
        if t in ("group", "interleave"):
            result = GeneratedModel(unordered=(t == "interleave"))
            for child in self.hoist_same_tag_siblings(list(node)):
                result += self.resolve_pattern(child, optional, parents)
            return result
        if t == "optional":
            result = GeneratedModel()
            for child in node:
                result += self.resolve_pattern(child, True, parents)
            return result
        if t in ("zeroOrMore", "oneOrMore"):
            return self.resolve_repeat(node, optional or t == "zeroOrMore", parents)
        if t == "ref":
            return self.resolve_ref_pattern(node.attrib["name"], optional, parents)
        if t == "choice":
            branches = list(node)
            elements = [self.unwrap_to_element(b) for b in branches]
            resolved = [e for e in elements if e is not None]
            if len(resolved) == len(branches):
                return self.partition_choice_by_tag(resolved, optional, parents)
            branch_parents = (*parents, "Variant")
            return self.merge_models(
                [self.resolve_pattern(b, parents=branch_parents) for b in branches],
                optional,
                parents,
            )
        if t in ("text", "data", "value"):
            return GeneratedModel(
                body=PythonType.from_relaxng(node, self), body_optional=optional
            )
        raise KeyError(f"<{t}> has no content")

    def resolve_element(
        self,
        node: Element,
        name_override: str | None = None,
        parents: tuple[str, ...] = (),
    ) -> str:
        if "name" not in node.attrib:
            return self.resolve_any_name(name_override)
        key = id(node)
        if name_override is None and key in self.element_cache:
            return self.element_cache[key]
        xml_tag = node.attrib["name"]
        cls_name = name_override or identifier(xml_tag)
        truncations_before = self.truncated_cycles
        model = GeneratedModel()
        for child in self.hoist_same_tag_siblings(list(node)):
            model += self.resolve_pattern(child, parents=(*parents, cls_name))
        name = self.emit(cls_name, xml_tag, model, parents, node.attrib.get("ns", ""))
        if name_override is None and self.truncated_cycles == truncations_before:
            self.element_cache[key] = name
        return name

    def resolve_any_name(self, name_override: str | None) -> str:
        return self.emit(name_override or "AnyElement", "*", GeneratedModel())

    def resolve_ref(self, name: str, parents: tuple[str, ...] = ()) -> PythonType:
        if name in self.ref_cache:
            return self.ref_cache[name]
        if name in self.refs_in_progress:
            return PythonType.opaque(f'"{identifier(name)}"')
        self.refs_in_progress.add(name)
        node = self.defines[name]
        truncations_before = self.truncated_cycles
        if tag(node) == "element":
            result = PythonType.opaque(
                self.resolve_element(node, identifier(name), parents)
            )
        else:
            result = PythonType.from_relaxng(node, self)
        self.refs_in_progress.discard(name)
        if self.truncated_cycles == truncations_before:
            self.ref_cache[name] = result
        return result

    def resolve_ref_pattern(
        self, name: str, optional: bool, parents: tuple[str, ...] = ()
    ) -> GeneratedModel:
        node = self.defines[name]
        if tag(node) == "element":
            cls = self.resolve_ref(name, parents)
            xml_tag = node.attrib.get("name")
            pyname = identifier(xml_tag) if xml_tag else identifier(name)
            ns = node.attrib.get("ns", "")
            return GeneratedModel(
                fields=[
                    GeneratedField(pyname, xml_tag, cls, "element", optional, ns=ns)
                ]
            )
        if name in self.mixins_in_progress:
            self.truncated_cycles += 1
            return GeneratedModel()
        self.mixins_in_progress.add(name)
        try:
            return self.resolve_pattern(node, optional, (*parents, identifier(name)))
        finally:
            self.mixins_in_progress.discard(name)

    def resolve_repeat(
        self, node: Element, optional: bool, parents: tuple[str, ...] = ()
    ) -> GeneratedModel:
        one_or_more = tag(node) == "oneOrMore"
        body = self.resolve_pattern(as_group(list(node)), parents=parents)
        fields = [
            f.repeated(
                optional or f.optional, 1 if (one_or_more and not f.optional) else None
            )
            for f in body.fields
        ]
        return GeneratedModel(fields=fields, unordered=True)

    def unwrap_to_element(self, node: Element) -> Element | None:
        t = tag(node)
        if t == "element":
            return node
        if t == "ref":
            target = self.defines.get(node.attrib["name"])
            return self.unwrap_to_element(target) if target is not None else None
        if t == "group":
            child = single_child(node)
            return self.unwrap_to_element(child) if child is not None else None
        return None

    def partition_choice_by_tag(
        self, elements: list[Element], optional: bool, parents: tuple[str, ...]
    ) -> GeneratedModel:
        by_tag: dict[tuple[str, str | None], list[Element]] = {}
        for e in elements:
            by_tag.setdefault(qualified_name(e), []).append(e)
        single_tag = len(by_tag) == 1
        fields = []
        for (ns, xml_tag), group in by_tag.items():
            cls = (
                self.resolve_element(group[0], parents=parents)
                if len(group) == 1
                else self.merge_elements_by_tag(xml_tag or "", ns, group, parents)
            )
            fields.append(
                GeneratedField(
                    identifier(xml_tag or ""),
                    xml_tag,
                    PythonType.opaque(cls),
                    "element",
                    optional or not single_tag,
                    ns=ns,
                )
            )
        return GeneratedModel(fields=fields, unordered=True)

    def merge_elements_by_tag(
        self, xml_tag: str, ns: str, group: list[Element], parents: tuple[str, ...]
    ) -> str:
        cls_name = identifier(xml_tag)
        branch_parents = (*parents, cls_name, "Variant")
        models = []
        for e in group:
            m = GeneratedModel()
            for child in self.hoist_same_tag_siblings(list(e)):
                m += self.resolve_pattern(child, parents=branch_parents)
            models.append(m)
        merged = self.merge_models(models, False, (*parents, cls_name))
        return self.emit(cls_name, xml_tag, merged, parents, ns)

    def merge_models(
        self,
        branches: list[GeneratedModel],
        optional: bool,
        parents: tuple[str, ...] = (),
    ) -> GeneratedModel:
        n = len(branches)
        by_key: dict[
            tuple[Literal["attr", "element"], str, str | None], list[GeneratedField]
        ] = {}
        for m in branches:
            for f in m.fields:
                by_key.setdefault((f.kind, f.ns, f.xml_name), []).append(f)
        fields = []
        for (kind, ns, xml_name), fs in by_key.items():
            types: list[PythonType] = []
            for f in fs:
                if f.type not in types:
                    types.append(f.type)
            if kind == "element" and len(types) > 1:
                types = self.remerge_element_variants(
                    types, xml_name or "", ns, parents
                )
            required = not optional and len(fs) == n and not any(f.optional for f in fs)
            min_lengths = {f.min_length for f in fs}
            min_length = (
                fs[0].min_length if required and len(min_lengths) == 1 else None
            )
            fields.append(
                GeneratedField(
                    fs[0].name,
                    xml_name,
                    PythonType.merge(types),
                    kind,
                    not required,
                    min_length,
                    ns,
                )
            )
        bodies: list[PythonType] = []
        body_count = 0
        for m in branches:
            if m.body is not None:
                body_count += 1
                if m.body not in bodies:
                    bodies.append(m.body)
        body = PythonType.merge(bodies) if bodies else None
        body_optional = optional or body_count < n
        return GeneratedModel(fields, body, body_optional, unordered=True)

    def remerge_element_variants(
        self,
        types: list[PythonType],
        xml_name: str,
        ns: str,
        parents: tuple[str, ...],
    ) -> list[PythonType]:
        names = [t.escape_identifier() for t in types]
        if all(name is not None and name in self.classes for name in names):
            sub_models = [self.classes[name].model for name in names if name]
            merged = self.merge_models(sub_models, False, parents)
            merged_name = self.emit(identifier(xml_name), xml_name, merged, parents, ns)
            return [PythonType.opaque(merged_name)]
        for t in types:
            cls = t.unwrap_escape_identifier()
            if cls is not None:
                self.forbid_extra(cls)
        return types

    def hoist_same_tag_siblings(self, children: list[Element]) -> list[Element]:
        def unwrapped(c: Element) -> tuple[Element | None, tuple[str, str] | None]:
            inner = single_child(c) if tag(c) == "optional" else None
            elem = self.unwrap_to_element(inner) if inner is not None else None
            if elem is None or not elem.attrib.get("name"):
                return inner, None
            return inner, (elem.attrib.get("ns", ""), elem.attrib["name"])

        by_tag: dict[tuple[str, str], list[Element]] = {}
        for c in children:
            inner, t = unwrapped(c)
            if inner is not None and t:
                by_tag.setdefault(t, []).append(inner)
        dupes = {t for t, group in by_tag.items() if len(group) > 1}
        if not dupes:
            return children
        merged, done = [], set()
        for c in children:
            _, t = unwrapped(c)
            if t not in dupes:
                merged.append(c)
            elif t not in done:
                done.add(t)
                choice = ET.Element(f"{{{NS}}}choice")
                choice.extend(by_tag[t])
                wrapper = ET.Element(f"{{{NS}}}optional")
                wrapper.append(choice)
                merged.append(wrapper)
        return merged

    def emit(
        self,
        name: str,
        xml_tag: str,
        model: GeneratedModel,
        parents: tuple[str, ...] = (),
        ns: str = "",
    ) -> str:
        """Doesn't decide a real name yet - just a placeholder, unique for this shape, standing
        in until assign_names sees every class that will ever exist and can name them all
        consistently (see there for why)."""
        shape = (xml_tag, ns, model.search_mode, model.render_lines(ns))
        if shape in self.class_by_shape:
            return self.class_by_shape[shape]
        placeholder = f"_pending_{len(self.classes)}"
        self.classes[placeholder] = GeneratedClass(placeholder, xml_tag, model, ns)
        self.pending[placeholder] = (name, parents)
        self.class_by_shape[shape] = placeholder
        return placeholder

    def forbid_extra(self, cls_name: str) -> None:
        if cls_name in self.classes:
            self.classes[cls_name].forbid_extra = True

    def assign_names(self) -> dict[str, str]:
        """Real class names, decided only once every class that will ever exist is known - never
        "first one resolved wins": if two+ classes want the same base name, ALL of them skip it
        and climb their own ancestor chain, instead of whichever happened to be resolved first
        keeping the short name and the rest being stuck disambiguating against it."""
        groups: dict[str, list[str]] = {}
        for placeholder, (base, _) in self.pending.items():
            groups.setdefault(base, []).append(placeholder)
        used: set[str] = set()
        rename: dict[str, str] = {}
        for base, placeholders in groups.items():
            allow_bare = len(placeholders) == 1
            for placeholder in placeholders:
                _, parents = self.pending[placeholder]
                rename[placeholder] = pick_name(base, parents, used, allow_bare)
        return rename

    def render(self, root_name: str, root_type: PythonType) -> str:
        rename = self.assign_names()
        classes = {rename[ph]: c.remap(rename) for ph, c in self.classes.items()}
        root_type = root_type.remap(rename)

        def refs(t: PythonType) -> list[str]:
            return [r for r in t.class_refs() if r in classes]

        reachable: set[str] = set()
        stack = refs(root_type)
        while stack:
            name = stack.pop()
            if name in reachable:
                continue
            reachable.add(name)
            model = classes[name].model
            for f in model.fields:
                stack += refs(f.type)
            if model.body is not None:
                stack += refs(model.body)
        kept = [c.render() for c in classes.values() if c.name in reachable]
        body = "\n\n".join(kept)
        return f"{PREAMBLE}{body}\n\n{root_name} = {root_type.render()}\n"


def convert(src: Path) -> str:
    root = ET.parse(src).getroot()
    defines, start = collect(root, src.parent)
    if start is None:
        raise Exception("No start element defined!")
    resolver = Resolver(defines)
    root_type = PythonType.from_relaxng(start, resolver)
    return resolver.render(src.stem, root_type)


def main() -> None:
    assert len(sys.argv) == 2
    print(convert(Path(sys.argv[1])))
